### ISSUE TITLE
run a process and read output until process finishes

### ISSUE THREAD

**Issue by matti** [socketry/async-process#1]
currently not possible

**Comment by ioquatix** [comment]
Feel free to submit a PR or a failing example.

**Comment by matti** [comment]
Just got this working, will make a pull request soon

**Comment by tonytonyjan** [comment]
@matti wonder how's the progress going? I also need this feature too.

**Comment by matti** [comment]
I lost my motivation after some async-* api changes, sorry I don't think I'll return to async-* ecosystem even if I like the basic idea of it.

**Comment by ioquatix** [comment]
> I lost my motivation after some async-* api changes, sorry I don't think I'll return to async-* ecosystem 

What changes are you thinking of?

**Comment by joekhoobyar** [comment]
@ioquatix  - I think that this would be a great feature.

Maybe an API like, `Async::Process.capture(*args, **options)`?

I have a nice working example of this, with similar semantics to `Kernel` backticks:

```
#!/usr/bin/env ruby
require 'async/io'
require 'async/process'

def async_pipe(*args)
  IO.pipe(*args).map { |io| Async::IO.try_convert(io) }
end

def async_capture(*args, **options)
  r, w = async_pipe
  options[:out] = w
  runner = Async do
    Async::Process.spawn(*args, **options)
    w.close
  end
  reader = Async do
    r.read
  ensure
    runner.wait
  end
end

Async.run do

  puts 'MPSTAT 1'
  mpstat1 = async_capture('mpstat 3 1')

  puts 'MPSTAT 2'
  mpstat2 = async_capture('mpstat 3 1')

  puts 'REPORT'
  puts mpstat1.wait
  puts mpstat2.wait
end
```

**Comment by ioquatix** [comment]
@joekhoobyar can you make a PR with your design? I may make further changes but it looks like a good start!

**Comment by ioquatix** [comment]
Also you can use `Async::IO.pipe`.

**Comment by joekhoobyar** [comment]
Sure, @ioquatix, will do.  On conference calls right now, but I will afterwards.

**Comment by ioquatix** [comment]
Implemented.
