### ISSUE TITLE
Blocking when process writes too much into a pipe?

### ISSUE THREAD

**Issue by leahneukirchen** [socketry/async-process#4]
I tried a variant of #1 where the process prints lots (or infinite) data.
However, when I remove the "head -n 30", or turn up the number to, say, 30000, the process blocks in epoll.
(Ruby 2.7.2p137 on Void Linux 5.9.8 x86_64/glibc 2.30).

```
require 'async/io'
require 'async/process'

Async do
  input, output = Async::IO.pipe
  status = Async::Process.spawn("yes | head -n 30", :out => output.io)
  output.close

  Async do
    while line = input.readpartial(10)
      p line
    end
  end

  puts status
end
```

Any ideas? Or am I holding it wrong?

I also noticed something like "echo foo; sleep 10; echo bar" does only yield results at once, even though readpartial is used.
Compare with:

```
input, output = IO.pipe
pid = Process.spawn("echo foo; sleep 1; echo bar", :out => output)
output.close

while line = input.readpartial(10)
  p line
end
```

**Comment by ioquatix** [comment]
Hmm, let me take a look.

**Comment by ioquatix** [comment]
I see. The problem is `Async::Process` will run until the process finishes. You need to start it in a nested task:

```
#!/usr/bin/env ruby

require 'async/io'
require 'async/process'

Async do
  input, output = Async::IO.pipe
  
  Async do
    status = Async::Process.spawn("yes", :out => output.io)
    output.close
  end
  
  Async do
    while line = input.readpartial(10)
      p line
    end
  end

  puts status
end
```

seems to be what you are trying to do.
